### ISSUE TITLE
selection rectangle position stays/renders in drag and drop & drop-ask is not provided with target

### ISSUE THREAD

**Issue by wael444** [phillbush/xfiles#25] opened 2023-01-13 14:22 UTC
```
drop-ask /home/wael/.profile
```

**Comment by wael444** [comment] 2023-01-13 14:24
https://user-images.githubusercontent.com/47404953/212342650-0e6f14ab-e121-410a-b2c9-afe4f7bc930e.mp4

**Comment by phillbush** [comment] 2023-01-13 18:29
I could not reproduce the error here, but I found the lines of code that could be causing it for you.
I think it should be fixed now.

**Closed** 2023-01-13 18:28 UTC
